title:        Liu Sida's Homepage
tagline:      'Liu Sida | Star Liu | liusida'
description:  'Machine Learning & Human Learning'
url:          http://liusida.com
version:      1.1.1
author:
  name:       'liusida'
  email:      ''
markdown:     kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:    pretty
highlighter:  true
paginate:     5
gems: [jekyll-paginate]