title: Sida Liu
subtitle: A Learner in the Complex World
description: >- # this means to ignore newlines until "baseurl:"
  The world is so complex that we cannot stop learning.

url: "https://liusida.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Cover
      url: /cover
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: sida.png
author: Sida Liu
author_bio: I am currently a M.S. graduate student in Morphology, Evolution & Cognition Laboratory at University of Vermont. I am interested in artificial intelligence, artificial life, and artificial environment.
# author_email: "learner.sida.liu@gmail.com"
author_location: Vermont, US
author_website_url: "https://liusida.github.io"
typewrite-text: You can pronounce my name as Star, since that's what it sounds in Mandarin Chinese.

author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: false

author_education_details:
              - college_logo: uvm-logo.png
                college_name: University of Vermont
                college_url: https://www.uvm.edu/
                college_degree: Master of Science in Complex Systems
                description: 2019-2021
                lab: Morphology, Evolution & Cognition Laboratory
                lab_url: https://www.meclab.org/
                visibility: true
              - college_logo: zju-logo.png
                college_name: Zhejiang University
                college_url: http://www.zju.edu.cn/english/
                college_degree: Bachelor of Science in Management
                description: 2000-2004
                visibility: true
author_project_details:
              - project_thumbnail: bigGuys_small.png
                project_title: gpuVoxels
                project_description: A voxel-based physics simulation for evolutionary robotics implemented in CUDA
                project_more_description: I noticed that researchers were using a voxel-based simulation <a href='https://github.com/jonhiller/Voxelyze'>Voxelyze</a> that runs on CPU, so I studied it and rewrote it so that it can run on multiple GPUs. Also I added some new features in the gpuVoxels to support new experiments.
                project_url: https://github.com/liusida/gpuVoxels/
                visibility: true
              - project_thumbnail: xenobots.png
                project_title: Xenobots
                project_description: Xenobots are automatically designed by computers to perform some desired function and built by combining together different biological tissues
                project_more_description: I just joined this project, and let's see what I can contribute.
                project_url: https://cdorgs.github.io/
                visibility: true
              - project_thumbnail: voxcraft.png
                project_title: Voxcraft
                project_description: Using hollow silicone blocks to make soft robots
                project_more_description: I just joined this project, and let's see what I can contribute.
                project_url: https://voxcraft.github.io/
                visibility: true

# social links
twitter_username: SidaLiu_UVM
github_username:  liusida
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: mrgyezqz

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-105744782-1

# Choose what to show ( can be true or false)
# show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
# algolia:
#   application_id: D9WA1YKTRQ
#   index_name: blog_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 8
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
