#!/bin/bash
COMMENT="default update"
if [ -z "$1" ]
	then
		echo "Using default comment: default update"
	else
		COMMENT=$1
	fi


cd ~/homepage/
jekyll build
git add -A
git commit -m "$COMMENT"
proxychains git push origin sources

cd _site/
git add -A
git commit -m "$COMMENT"
proxychains git push origin master

echo "Done."